version: '3'
services:
  web:
    build: .
    ports:
     - "5001-5003:5000"
    volumes:
     - .:/code
    command: flask run --host 0.0.0.0
  redis:
    image: "redis:alpine"
  ngin:
    image: "nginx:1.13.5-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
