version: '3'

services:
  flask:
    image: python:3.6
    ports:
      - "5000:5000"
    volumes:
      - "./src:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: >
      bash -c "cd /projects
      && pip install -r requirements.txt
      && flask run --host 0.0.0.0 --port 5000"
